version: '3.8'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    networks:
      - my-network
  web:
    build: .
    command: bash -c "sleep 3 && rm -f tmp/pids/server.pid && bundle exec rails db:setup && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/var/www/app
      - bundle:/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - my-network
      
volumes:
  bundle:

networks:
  my-network:
